version: '3.8'

services:
    copilotadherence:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # - ASPNETCORE_HTTP_PORTS=8080
            # - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        ports:
            - "31500:80"
            - "31501:443"
        volumes:
            - C:\Users\fernando\.aspnet\https:/https:ro  # location of the dev-cert, read-only mode

        build: 
            context: CopilotAdherence
            dockerfile: Dockerfile
    # volumes:
    #   - C:\Users\fernando\.aspnet\https:/https:ro  # location of the dev-cert
        depends_on:
          - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"
        volumes:
        - mongodata:/data/db
volumes:
    mongodata: